const names = {
  female: [
    'Adrienne Barboned',
    "Alicia Bluestones",
    'Anna Can Dick',
    'Anna Packed In',
    'Annal Gunge',
    'Anne Bangcroft',
    'Anne Hathawang',
    'Annette Boning',
    'Audrey Rugburn',
    'Bette Diddler',
    'Carrie Fishsmell',
    "Catherine Zeta-Moans",
    "Daisychain Ridley",
    "Diane Cheatin'",
    "DoMe Moore",
    "Elizabeth Boinks",
    'Emma Boned',
    'Fapke Janssen',
    'Faye Runaway',
    "Florence Pubes",
    'Glenn Closer',
    'Helena Bangem Carter',
    'Hillary Skank',
    'Holly Humper',
    'Imogen Toots',
    'Jamie Lee Beef Curtains',
    'Jane Fondle',
    "Jessica Handy",
    'Julia Knobberts',
    'Kate Winslut',
    'Katherine Rugburn',
    "Kathy 'bates",
    'Lorraine Cocko',
    "Loli Ringwald",
    "Lucy Goo",
    "Madeline Stowe-it-deep-in-there",
    "Maggie's Jillinhard",
    'Mary Steamvirgin',
    'Meryl Streaks',
    'Michelle Pfluffer',
    'Natalie Porkman',
    'Peepee Neuwirth',
    "Quimta Brunson",
    'Rhea See Horny',
    'Sandra Bullcock',
    'SigHorny Weaver',
    'Tilda Sweatin',
    "Tori's Spinning",
    'Vivian Lay'
  ],
  male: [
    "Aarod Pull",
    "Alan Thicc",
    "Armie Hummer",
    "Benedict Cumbersomebatch",
    "Billy Bob Thrustin'",
    "Blowin' Atkinson",
    "Bryan Crammston",
    "Ben Stillinher",
    "Bob Oldekink",
    "Christian LayedHer",
    "Clit Eastwood",
    "Channing TaintYum",
    "Chris Splatt",
    "Colin Filth",
    "Corey Felt Men",
    "Cuck Norris",
    "Dick Van Lesbian",
    "Dustin Boffman",
    'Dwayne “The Cock” Johnson',
    'Ed Semgma, Jr.',
    "Gape Vagoda",
    "Gerard Butt",
    "Giancarlo Espesemen-o",
    "Giovanni Ribbedisi",
    "Going Downey, Jr",
    "Gregory Pecker",
    "Huge Jack, Man",
    "Jake Fillin All",
    "James Gandalf Weenie",
    "Johnathan Bonks",
    "Keith Gayvid",
    "Kevin Spanky",
    "Idris Elbowdeep",
    "Jack Lemmon Party",
    "Loose Willis",
    "Michael DickKeen",
    "Paul Blewman",
    "Peeonyou Reeves",
    "Power O'Toole",
    "Phillip Seemore Buffmen",
    "Raul Pudd",
    "Robert Splattinson",
    "RutGirl Harder",
    "Russell Blowe",
    "Seann William Slutt",
    "Squirt Reynolds",
    "Taka Wild Titties",
    "Tom Diddleson",
    "Tom Spanks",
    "Valtrex Kilmer",
    "Yoni Depp"
  ]
};