const names = {
  female: [
    'Adrienne Barboned',
    "Alicia Bluestones",
    'Amanda Sayfilth',
    'Anna Can Dick',
    'Anna Packed In',
    'Annal Gunge',
    'Anne Bangcroft',
    'Anne Hathawang',
    'Annette Boning',
    'Audrey Rugburn',
    'Bette Diddler',
    'Brittany Snowbunny',
    'Carrie Fishsmell',
    "Catherine Zeta-Moans",
    "Daisychain Ridley",
    "Diane Cheatin'",
    "DoMe Moore",
    "Elizabeth Boinks",
    'Emma Boned',
    'Fapke Janssen',
    'Faye Runaway',
    "Florence Pubes",
    'Glenn Closer',
    'Helena Bangem Carter',
    'Hillary Skank',
    'Holly Humper',
    'Imogen Toots',
    'Jamie Lee Beef Curtains',
    'Jane Fondle',
    "Jessica Handy",
    'Julia Knobberts',
    'Kate Winslut',
    'Katherine Rugburn',
    "Kathy 'bates",
    'Lorraine Cocko',
    "Loli Ringwald",
    "Lucy Goo",
    "Madeline Stowe-it-deep-in-there",
    "Maggie's Jillinhard",
    "Margot Ribjobbie",
    'Mary Steamvirgin',
    'Meryl Streaks',
    'Michelle Pfluffer',
    "Milfie Booty Brown",
    'Natalie Porkman',
    'Peepee Neuwirth',
    'Portia de Pussi',
    "Quimta Brunson",
    'Rhea See Horny',
    'Sam Smellibutt',
    'Sandra Bullcock',
    'SigHorny Weaver',
    "Sydney Sweetloads",
    'Tilda Sweatin',
    "Tori's Spinning",
    'Vivian Lay',
    'Riding Winona'
  ],
  male: [
    "Aarod Pull",
    "Alec Baldtwat",
    "Alan Thicc",
    "Armie Hummer",
    "Benedict Cumbersomebatch",
    "Billy Bob Thrustin'",
    "Blowin' Atkinson",
    "Bryan Crammston",
    "Ben Stillinher",
    "Bob Oldekink",
    "Christian LayedHer",
    "Clit Eastwood",
    "Channing TaintYum",
    "Chris Splatt",
    "Colin Filth",
    "Corey Felt Men",
    "Cuck Norris",
    "Dick Van Lesbian",
    "Dick Cage",
    "Dustin Boffman",
    'Dwayne “The Cock” Johnson',
    'Ed Semgma, Jr.',
    "Gape Vagoda",
    "Gerard Butt",
    "Giancarlo Espesemen-o",
    "Giovanni Ribbedisi",
    "Going Downey, Jr",
    "Gregory Pecker",
    "Huge Jack, Man",
    "Jake Fillin All",
    "James Gandalf Weenie",
    "Johnathan Bonks",
    "Keith Gayvid",
    "Kevin Spanky",
    "Idris Elbowdeep",
    "Jack Lemmon Party",
    "James Nicebutt",
    "Jason Momboner",
    "Loose Willis",
    "Michael DickKeen",
    "Paul Blewman",
    "Peeonyou Reeves",
    "Power O'Toole",
    "Phillip Seemore Buffmen",
    "Raul Pudd",
    "Robert Splattinson",
    "RutGirl Harder",
    "Russell Blowe",
    "Seann William Slutt",
    "Squirt Reynolds",
    "Taika Wild Titties",
    "Timothée Challenge Lay",
    "Tom Diddleson",
    "Tom Spanks",
    "Valtrex Kilmer",
    "Yoni Depp",
    'Walton Gaggins'
  ]
};